services:
  # Production service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env

  # Nginx service
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Mount the live certificates from the host into the container
      - /etc/letsencrypt:/etc/nginx/certs:ro
    depends_on:
      - app
